### ISSUE TITLE
추가버튼 똑같은거다시누르고(2회이상)제출시 에러

### ISSUE THREAD

**Issue by hasfijdhifasbekjvbska** [rlatnseo14/schoolphp#3]

**Comment by rlatnseo14** [comment]
commit
[https://github.com/rlatnseo14/schoolphp/commit/5a0bd7b59963f7e99b700ba9f1643f6e962cf2a1](url)

if($b+1 === sizeof($temparr)){}로 인해서 2회 이상 클릭시 if문을 통과했었던 것이다..
